name: my workflow
on: commit_comment
jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: printing
        run: echo "hello world"
      - name: Run a multi-line script
        run: |
          echo "hi everybody"
          echo "hi"
