name: my workflow
on: workflow_call
jobs:
    runs-on: ubuntu-latest
    steps:
      firstjob:
      - name: printing
        run: echo "hello world"
      - name: Run a multi-line script
        run: |
          echo "hi everybody"
          echo "hi"
