name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag my-image-name:v1
        docker run -d -p 80:80 my-image-name:v1 
        curl localhost:80

    - name: Upload image
      uses: ishworkh/docker-image-artifact-upload@v1
      with:
        name: first_image
        image: "my-image-name:v1"
  deploy:
  
    runs-on: ubuntu-latest
    steps:
    - name: Download image
      uses: ishworkh/docker-image-artifact-download@v1
      with:
        name: first_image

       


