name: Docker image cicd

on:
 
  workflow_dispatch:  

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag my-image-name:v1
        docker run -d -p 80:80 myimage-name:v1 
        pwd
        ls
        curl http://localhost:80
        
      
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        echo "${{ secrets.API_KEY }}" | docker login -u "rajudruva2@gmail.com" --password-stdin
        docker image build -t myartifactory1405.jfrog.io/docker/myimage-name:v1 .
        docker push myartifactory1405.jfrog.io/docker/myimage-name:v1 


