name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:v1

    - name: Upload image
      uses: ishworkh/docker-image-artifact-upload@v1
      with:
        image: "my-image-name:v1"
    - name: docker run
      run: |
        sudo apt install docker.io -y
        docker run -it my-image-name:v1 /bin/bash


